/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-01-31 07:26:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.javalex.ex.Session.SessionUtil;

public final class customerservice_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.javalex.ex.Session.SessionUtil");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<!-- basic -->\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!-- mobile metas -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"viewport\" content=\"initial-scale=1, maximum-scale=1\">\r\n");
      out.write("<!-- site metas -->\r\n");
      out.write("<title>Search</title>\r\n");
      out.write("<meta name=\"keywords\" content=\"\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">	\r\n");
      out.write("<!-- bootstrap css -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("<!-- style css -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\">\r\n");
      out.write("<!-- Responsive-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/responsive.css\">\r\n");
      out.write("<!-- fevicon -->\r\n");
      out.write("<link rel=\"icon\" href=\"images/fevicon.png\" type=\"image/gif\" />\r\n");
      out.write("<!-- Scrollbar Custom CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/jquery.mCustomScrollbar.min.css\">\r\n");
      out.write("<!-- Tweaks for older IEs-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css\">\r\n");
      out.write("<!-- owl stylesheets --> \r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesoeet\" href=\"css/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css\" media=\"screen\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- header section start-->\r\n");
      out.write("	<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\r\n");
      out.write("        <a class=\"logo\" href=\"#\"><img src=\"images/klogo.jpg\"></a>\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav\" aria-controls=\"navbarNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("        <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("            <ul class=\"navbar-nav\">\r\n");
      out.write("              <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"index.jsp\">홈</a>\r\n");
      out.write("             </li>\r\n");
      out.write("             <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"search_jobs.jsp\">채용정보</a>\r\n");
      out.write("             </li>\r\n");
      out.write("             <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"recurments.jsp\">채용직별 구인</a>\r\n");
      out.write("             </li>\r\n");
      out.write("             <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"companies.jsp\">기업정보</a>\r\n");
      out.write("             </li>\r\n");
      out.write("             <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"services.jsp\">커리어상담</a>\r\n");
      out.write("             </li>\r\n");
      out.write("             <li class=\"nav-item\">\r\n");
      out.write("                <a class=\"nav-link\" href=\"customerservice.jsp\">고객센터</a>\r\n");
      out.write("             </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("         <!-- 로그인 상태에 따라 다른 링크를 출력 -->\r\n");
      out.write("                    ");
 if (SessionUtil.checkLogin(request)) { 
      out.write("\r\n");
      out.write("                     	<div class=\"login_text Last\"><a href=\"mypage.do\">마이페이지</a></div>\r\n");
      out.write("                        <div class=\"login_text\"><a href=\"logout.do\">로그아웃</a></div>\r\n");
      out.write("                    ");
 } else { 
      out.write("\r\n");
      out.write("                        <div class=\"login_text\"><a href=\"login.jsp\">로그인</a></div>\r\n");
      out.write("                    ");
 } 
      out.write("\r\n");
      out.write("              \r\n");
      out.write("    </nav>\r\n");
      out.write("	<!-- header section start-->\r\n");
      out.write("  <!-- search jobs section start-->\r\n");
      out.write("  <div class=\"search_section layout_padding\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"logo_1\"><img src=\"images/logo-2.png\"></div>\r\n");
      out.write("          <div class=\"row box\">\r\n");
      out.write("              <div class=\"col-md-6\">\r\n");
      out.write("                  <h1 class=\"what_text\">What</h1>\r\n");
      out.write("                  <p class=\"city_text\">job title, keywords, or company</p>\r\n");
      out.write("                  <div class=\"main\"> \r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" placeholder=\"Search this blog\">\r\n");
      out.write("                        <div class=\"input-group-append\">\r\n");
      out.write("                            <button class=\"btn btn-secondary\" type=\"button\">\r\n");
      out.write("                                <i class=\"fa fa-search\"></i>\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div> \r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-6\">\r\n");
      out.write("                  <h1 class=\"what_text\">Where</h1>\r\n");
      out.write("                  <p class=\"city_text\">city, state, or pin code</p>\r\n");
      out.write("                  <div>\r\n");
      out.write("                      <div class=\"main\"> \r\n");
      out.write("                          <div class=\"input-group\">\r\n");
      out.write("                              <input type=\"text\" class=\"form-control\" placeholder=\"Ahmedabad, Gujarat\">\r\n");
      out.write("                              <div class=\"input-group-append\">\r\n");
      out.write("                                  <button class=\"btn btn-secondary\" type=\"button\">\r\n");
      out.write("                                      <i class=\"fa fa-map-marker\"></i>\r\n");
      out.write("                                  </button>\r\n");
      out.write("                              </div>\r\n");
      out.write("                          </div> \r\n");
      out.write("                      </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"\">\r\n");
      out.write("            <button class=\"find_bt\">Find Jobs</button>\r\n");
      out.write("          </div>\r\n");
      out.write("      </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- search jobs section end-->\r\n");
      out.write("\r\n");
      out.write("  <!-- footer section start-->\r\n");
      out.write("  <div class=\"footer_section layout_padding\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <h1 class=\"subscribr_text\">Subscribe Now</h1>\r\n");
      out.write("      <p class=\"lorem_text\">There are many variations of passages of Lorem Ipsum available, but the majority have </p>\r\n");
      out.write("      <div class=\"box_main_2\">\r\n");
      out.write("          <textarea type=\"\" class=\"email_bt_2\" placeholder=\"Enter Your Email\" name=\"\"></textarea>\r\n");
      out.write("        </div>\r\n");
      out.write("        <button class=\"subscribe_bt_2\"><a href=\"#\">Subscribe</a></button>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- footer section end-->\r\n");
      out.write("  <!-- copyright section start-->\r\n");
      out.write("  <div class=\"copyright_section\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("          <p class=\"copyright_text\">Copyright 2024 All Right Reserved By AI TEAM 2.<a href=\"http://www.kb.or.kr/\">경북산업직업전문학교</a></p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("          <p class=\"cookies_text\"></p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- copyright section end-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Javascript files-->\r\n");
      out.write("    <script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"js/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("      <script src=\"js/jquery-3.0.0.min.js\"></script>\r\n");
      out.write("      <script src=\"js/plugin.js\"></script>\r\n");
      out.write("      <!-- sidebar -->\r\n");
      out.write("      <script src=\"js/jquery.mCustomScrollbar.concat.min.js\"></script>\r\n");
      out.write("      <script src=\"js/custom.js\"></script>\r\n");
      out.write("      <!-- javascript --> \r\n");
      out.write("      <script src=\"js/owl.carousel.js\"></script>\r\n");
      out.write("      <script src=\"https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js\"></script>\r\n");
      out.write("      <script>\r\n");
      out.write("      $(document).ready(function(){\r\n");
      out.write("      $(\".fancybox\").fancybox({\r\n");
      out.write("         openEffect: \"none\",\r\n");
      out.write("         closeEffect: \"none\"\r\n");
      out.write("         });\r\n");
      out.write("      // 로그아웃 성공 시에만 alert 표시\r\n");
      out.write("      var logoutSuccess = '");
      out.print( request.getParameter("logoutSuccess") );
      out.write("';\r\n");
      out.write("      if (logoutSuccess === \"true\") {\r\n");
      out.write("          alert(\"로그아웃되었습니다.\");\r\n");
      out.write("      }\r\n");
      out.write("      });\r\n");
      out.write("        \r\n");
      out.write("      </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
