/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-02-08 07:29:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.javalex.ex.Session.SessionUtil;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.javalex.ex.Session.SessionUtil");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<!-- basic -->\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!-- mobile metas -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"viewport\" content=\"initial-scale=1, maximum-scale=1\">\r\n");
      out.write("<!-- site metas -->\r\n");
      out.write("<title>Login</title>\r\n");
      out.write("<meta name=\"keywords\" content=\"\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("<!-- bootstrap css -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("<!-- style css -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\">\r\n");
      out.write("<!-- Responsive-->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/responsive.css\">\r\n");
      out.write("<!-- fevicon -->\r\n");
      out.write("<link rel=\"icon\" href=\"images/fevicon.png\" type=\"image/gif\" />\r\n");
      out.write("<!-- Scrollbar Custom CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/jquery.mCustomScrollbar.min.css\">\r\n");
      out.write("<!-- Tweaks for older IEs-->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css\">\r\n");
      out.write("<!-- owl stylesheets -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\">\r\n");
      out.write("<link rel=\"stylesoeet\" href=\"css/owl.theme.default.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css\"\r\n");
      out.write("	media=\"screen\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- header section start-->\r\n");
      out.write("	<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\r\n");
      out.write("		<a class=\"logo\" href=\"index.jsp\"><img src=\"images/klogo.jpg\"></a>\r\n");
      out.write("		<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("			data-target=\"#navbarNav\" aria-controls=\"navbarNav\"\r\n");
      out.write("			aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("			<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("		</button>\r\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"navbarNav\">\r\n");
      out.write("			<ul class=\"navbar-nav\">\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"index.jsp\">홈</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"recurments.jsp\">채용정보</a></li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"companies.jsp\">기업소개</a>\r\n");
      out.write("				</li>\r\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"services.jsp\">커리어상담</a>\r\n");
      out.write("				</li>\r\n");
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- 로그인 상태에 따라 다른 링크를 출력 -->\r\n");
      out.write("		");

		if (SessionUtil.checkLogin(request)) {
		
      out.write("\r\n");
      out.write("		<div class=\"login_text Last\">\r\n");
      out.write("			<a href=\"select.do\">마이페이지</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"login_text\">\r\n");
      out.write("			<a href=\"logout.do\">로그아웃</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		");

		} else {
		
      out.write("\r\n");
      out.write("		<div class=\"login_text\">\r\n");
      out.write("			<a href=\"login.jsp\">로그인</a>\r\n");
      out.write("		</div>\r\n");
      out.write("		");

		}
		
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</nav>\r\n");
      out.write("	<!-- header section end-->\r\n");
      out.write("	<!-- login section start-->\r\n");
      out.write("	<div class=\"services_section\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<h1 class=\"services_text\">로그인·회원가입</h1>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"login_section\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-sm-9 col-md-7 col-lg-5 mx-auto\">\r\n");
      out.write("					<div class=\"card card-signin my-5\">\r\n");
      out.write("						<div class=\"card-body\">\r\n");
      out.write("							<h5 class=\"card-title text-center\">로그인</h5>\r\n");
      out.write("							<form action=\"login.do\" class=\"form-signin\">\r\n");
      out.write("								<div class=\"form-label-group\">\r\n");
      out.write("									<input type=\"text\" id=\"inputId\" name=\"id\" class=\"form-control\"\r\n");
      out.write("										placeholder=\"Email address\" required autofocus> <label\r\n");
      out.write("										for=\"inputId\">아이디 입력</label>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<div class=\"form-label-group\">\r\n");
      out.write("									<input type=\"password\" id=\"inputPassword\" name=\"pw\"\r\n");
      out.write("										class=\"form-control\" placeholder=\"Password\" required>\r\n");
      out.write("									<label for=\"inputPassword\">비밀번호 입력</label>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("								<button class=\"btn btn-lg btn-primary btn-block text-uppercase\"\r\n");
      out.write("									type=\"submit\">로그인 하기</button>\r\n");
      out.write("								<hr class=\"my-4\">\r\n");
      out.write("								<!--<button class=\"btn btn-lg btn-google btn-block text-uppercase\" type=\"submit\"><i class=\"fab fa-google mr-2\"></i>구글 계정으로 로그인 하기</button>\r\n");
      out.write("              <button class=\"btn btn-lg btn-facebook btn-block text-uppercase\" type=\"submit\"><i class=\"fab fa-facebook-f mr-2\"></i> 페이스북 계정으로 로그인 하기</button>-->\r\n");
      out.write("								<p>\r\n");
      out.write("									만약 계정이 없으시다면?<a href=\"SignUp.html\"\r\n");
      out.write("										style=\"margin-left: 110px; color: blue\"><b>회원가입</b></a>\r\n");
      out.write("								</p>\r\n");
      out.write("								<a href=\"#\"\r\n");
      out.write("									onclick=\"window.open('searchID.html','아이디찾기','width =00','height=00' )\">아이디찾기</a>\r\n");
      out.write("								<a href=\"#\"\r\n");
      out.write("									onclick=\"window.open('searchPW.html','비밀번호찾기','width =00','height=00')\">비밀번호찾기</a>\r\n");
      out.write("							</form>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- login section end-->\r\n");
      out.write("\r\n");
      out.write("	<!-- footer section start-->\r\n");
      out.write("	<div class=\"footer_section layout_padding\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<h1 class=\"subscribr_text\">구직정보 알림받기</h1>\r\n");
      out.write("			<p class=\"lorem_text\">회원가입 없이도 구직정보를 받고싶으시다면 이메일을 입력해 주세요. </p>\r\n");
      out.write("			<div class=\"box_main_2\">\r\n");
      out.write("			    <form action=\"guest.do\" method=\"post\" id=\"guestForm\">\r\n");
      out.write("			    <input type=\"text\" class=\"email_bt_2\" placeholder=\"Enter Your Email\" name=\"guestEmail\" id=\"guestEmail\"> \r\n");
      out.write("		     \r\n");
      out.write("		    <input type=\"submit\" value=\"입력\" class=\"subscribe_bt_2\" onclick=\"guestAlert()\">\r\n");
      out.write("		    	</form>\r\n");
      out.write("		   		 </div>\r\n");
      out.write("		   \r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("		<!-- footer section end-->\r\n");
      out.write("		<!-- copyright section start-->\r\n");
      out.write("		<div class=\"copyright_section\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-md-6\">\r\n");
      out.write("						<p class=\"copyright_text\">\r\n");
      out.write("							Copyright 2020 All Right Reserved By.<a\r\n");
      out.write("								href=\"https://html.design\"> Free html Templates</a>\r\n");
      out.write("						</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-md-6\">\r\n");
      out.write("						<p class=\"cookies_text\">Cookies, Privacy and Terms</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- copyright section end-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- Javascript files-->\r\n");
      out.write("		<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("		<script src=\"js/popper.min.js\"></script>\r\n");
      out.write("		<script src=\"js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("		<script src=\"js/jquery-3.0.0.min.js\"></script>\r\n");
      out.write("		<script src=\"js/plugin.js\"></script>\r\n");
      out.write("		<!-- sidebar -->\r\n");
      out.write("		<script src=\"js/jquery.mCustomScrollbar.concat.min.js\"></script>\r\n");
      out.write("		<script src=\"js/custom.js\"></script>\r\n");
      out.write("		<!-- javascript -->\r\n");
      out.write("		<script src=\"js/owl.carousel.js\"></script>\r\n");
      out.write("		<script\r\n");
      out.write("			src=\"https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js\"></script>\r\n");
      out.write("		\r\n");
      out.write("		<script src=\"js/guestAlert.js\"></script>\r\n");
      out.write("		 <script>\r\n");
      out.write("		 $(document).ready(function(){\r\n");
      out.write("      $(\".fancybox\").fancybox({\r\n");
      out.write("         openEffect: \"none\",\r\n");
      out.write("         closeEffect: \"none\"\r\n");
      out.write("         });\r\n");
      out.write("      // 로그인 실패했을때\r\n");
      out.write("      var loginError = '");
      out.print( request.getParameter("loginError") );
      out.write("';\r\n");
      out.write("      if (loginError === \"true\") {\r\n");
      out.write("          alert(\"입력하신 정보가 올바르지 않습니다.\");\r\n");
      out.write("      }\r\n");
      out.write("   		// 로그아웃 성공 시에만 alert 표시\r\n");
      out.write("      var logoutSuccess = '");
      out.print( request.getParameter("logoutSuccess") );
      out.write("';\r\n");
      out.write("      if (logoutSuccess === \"true\") {\r\n");
      out.write("          alert(\"로그아웃되었습니다.\");\r\n");
      out.write("      }\r\n");
      out.write("      });\r\n");
      out.write("		 </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
